language: python
python: 3.6

branches:
  only:
    - master

env:
  matrix:
    - TASK=tests
    - TASK=isort
    - TASK=flake8

install:
  - if [ $TASK = tests ]; then pip install requests-oauthlib; fi
  - if [ $TASK == isort ]; then pip install isort; fi
  - if [ $TASK == flake8 ]; then pip install flake8; fi

script:
  - if [ $TASK = tests ]; then python setup.py test; fi
  - if [ $TASK = isort ]; then isort --diff --check-only; fi
  - if [ $TASK = flake8 ]; then flake8; fi

notifications:
  email: false
